name: C++ CI on Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest 

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install CMake and Visual Studio Build Tools
      run: |
        choco install cmake --version 3.21.0
        choco install visualstudio2019buildtools

    - name: Build project with CMake
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build .

    - name: Run tests
      run: |
        cd build
        .\test_example.exe   
